# Generated by Django 4.2.16 on 2024-10-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="path/to/default/image.jpg", upload_to="blog_image/%Y/%m/%d/"
            ),
        ),
    ]
