# Generated by Django 4.2.16 on 2024-11-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                default="path/to/default/image.jpg",
                null=True,
                upload_to="blog_image/%Y/%m/%d/",
            ),
        ),
    ]
